name: Manual Triggers
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
      version:
        description: Version to deploy
        required: false
        default: latest
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
